global using MediatR;
global using Victory.Application.Desktop.Interfaces;
global using Victory.Application.Features.Bookings;
global using Victory.Application.Features.Foods;
global using Victory.Application.Features.Messages;
global using Victory.Application.Features.Subscribers;
global using Victory.Application.Features.Users;
global using Victory.Domain.Models;
global using Victory.Infra.Core.Enums;