global using API.Data.Repositories.Abstract;
global using API.Services.Abstract.Bookings;
global using API.Services.Abstract.Cache;
global using API.Services.Abstract.Foods;
global using API.Services.Abstract.Messages;
global using API.Services.Abstract.Subscribers;
global using Microsoft.Extensions.Caching.Memory;
global using VictoryRestaurant.Entities;
global using VictoryRestaurant.Enums.Food;